var nhmcStatic = {
    "breaks": [10, 15, 20, 25, 30, 40, 50, 100],
    "colors": ["#ffffd9", "#edf8b1", "#c7e9b4", "#7fcdbb", "#41b6c4", "#1d91c0", "#225ea8", "#0c2c84"],
    "decimalPlaces": 0,
    "suffix": "%",
    "areas": {
        "Alabama": 49,
        "Alaska": 26,
        "Arizona": 23,
        "Arkansas": 53,
        "California": 18,
        "Colorado": 23,
        "Connecticut": 10,
        "Delaware": 15,
        "District of Columbia": 15,
        "Florida": 25,
        "Georgia": 38,
        "Hawaii": 26,
        "Idaho": 22,
        "Illinois": 19,
        "Indiana": 34,
        "Iowa": 24,
        "Kansas": 29,
        "Kentucky": 49,
        "Louisiana": 31,
        "Maine": 15,
        "Maryland": 15,
        "Massachusetts": 11,
        "Michigan": 26,
        "Minnesota": 21,
        "Mississippi": 47,
        "Missouri": 37,
        "Montana": 26,
        "Nebraska": 21,
        "Nevada": 13,
        "New Hampshire": 11,
        "New Jersey": 12,
        "New Mexico": 25,
        "New York": 11,
        "North Carolina": 41,
        "North Dakota": 24,
        "Ohio": 26,
        "Oklahoma": 53,
        "Oregon": 30,
        "Pennsylvania": 18,
        "Rhode Island": 10,
        "South Carolina": 45,
        "South Dakota": 24,
        "Tennessee": 51,
        "Texas": 34,
        "Utah": 7,
        "Vermont": 11,
        "Virginia": 31,
        "Washington": 25,
        "West Virginia": 36,
        "Wisconsin": 24,
        "Wyoming": 26
    }
};
